### ISSUE TITLE
[QA ver1.0] Resolves main page design

### ISSUE THREAD

**Issue by yumzen** [kahluaband/Homepage_FE_release#10]
1. 이미지 grid와 안맞음
<img width="389" alt="image" src="https://github.com/kahluaband/Homepage_FE_release/assets/109282927/638e4181-02d6-47b7-8bfe-35c9a90bceea">

2. CD.. 그냥 이젠 겹쳐도 안이상해보이는 병에 걸림
<img width="544" alt="image" src="https://github.com/kahluaband/Homepage_FE_release/assets/109282927/5e13cef0-3569-4898-a3c8-ff2d2acfd293">

3. 글씨 가려지는 건 좀 그런듯..
<img width="409" alt="image" src="https://github.com/kahluaband/Homepage_FE_release/assets/109282927/56895a48-4a21-48c9-a891-7d32586d206f">

그리고 아이폰11로 봤을 때 밑에 여백 안생김! 아주 깔끔함. CD가 유튜브랑 조금 겹치긴 하는데 이정돈 봐줄만함.

**Comment by yumzen** [comment]
- 전체적으로 크기를 %로 설정해두었는데 % -> vw나 px로 고정값을 넣어야 모든 디바이스에서 일정할듯
- 전체 height을 pc로 반응형 확인 시에는 문제가 없지만 실제 디바이스에서 볼 경우 밑에 여백이 생김 
- 전체 height을 고정 값으로 지정하는게 모든 디바이스에서 깨지지않고 일정하게 나올듯

**Comment by caminobelllo** [comment]
굳
